name    'ericsson-observium'
version '0.1.0'
source 'git://github.com/Ericsson/puppet-module-observium.git'
author 'jwennerberg'
license 'Apache License, Version 2.0'
summary 'Manage Observium'
description 'Manages Observium, including users and devices'
project_page 'https://github.com/Ericsson/puppet-module-observium'

dependency 'puppetlabs/stdlib', '3.2.x'
dependency 'ghoneycutt/apache', '>= 0.0.1'
